/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaJudger_SandBox_Jni */

#ifndef _Included_JavaJudger_SandBox_Jni
#define _Included_JavaJudger_SandBox_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaJudger_SandBox_Jni
 * Method:    jniUpdateIntegerConfs
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_JavaJudger_SandBox_Jni_jniUpdateIntegerConfs
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     JavaJudger_SandBox_Jni
 * Method:    jniUpdateInputFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JavaJudger_SandBox_Jni_jniUpdateInputFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JavaJudger_SandBox_Jni
 * Method:    jniUpdateOutputFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JavaJudger_SandBox_Jni_jniUpdateOutputFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JavaJudger_SandBox_Jni
 * Method:    jniUpdateErrorFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JavaJudger_SandBox_Jni_jniUpdateErrorFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JavaJudger_SandBox_Jni
 * Method:    jniUpdateExecuteableFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JavaJudger_SandBox_Jni_jniUpdateExecuteableFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JavaJudger_SandBox_Jni
 * Method:    jniRun
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaJudger_SandBox_Jni_jniRun
  (JNIEnv *, jobject);

/*
 * Class:     JavaJudger_SandBox_Jni
 * Method:    jniGetMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_JavaJudger_SandBox_Jni_jniGetMemory
  (JNIEnv *, jobject);

/*
 * Class:     JavaJudger_SandBox_Jni
 * Method:    jniGetResultInfo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JavaJudger_SandBox_Jni_jniGetResultInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     JavaJudger_SandBox_Jni
 * Method:    jniIgnoringCompare
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_JavaJudger_SandBox_Jni_jniIgnoringCompare
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     JavaJudger_SandBox_Jni
 * Method:    jniRunCommand
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JavaJudger_SandBox_Jni_jniRunCommand
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JavaJudger_SandBox_Jni
 * Method:    jniSpecialJudge
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JavaJudger_SandBox_Jni_jniSpecialJudge
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
